#' 05_code_export 
#'
#' @description A fct function
#'
#' @return The return value, if any, from executing the function.
#'
#' @noRd
# Helper functions for code generation
generate_rmd_header <- function() {
  paste0(
    "---\n",
    "title: \"Clinical Trial Response Analysis\"\n",
    "author: \"Generated by dashResponse\"\n",
    "date: \"`r Sys.Date()`\"\n",
    "output: \n",
    "  html_document:\n",
    "    toc: true\n",
    "    toc_float: true\n",
    "    code_folding: show\n",
    "---\n\n",
    "# Clinical Trial Response Analysis\n\n",
    "This document contains reproducible code generated from your dashResponse analysis.\n\n"
  )
}

generate_qmd_header <- function() {
  paste0(
    "---\n",
    "title: \"Clinical Trial Response Analysis\"\n",
    "author: \"Generated by dashResponse\"\n",
    "date: today\n",
    "format: \n",
    "  html:\n",
    "    toc: true\n",
    "    code-fold: show\n",
    "---\n\n",
    "# Clinical Trial Response Analysis\n\n",
    "This document contains reproducible code generated from your dashResponse analysis.\n\n"
  )
}

generate_r_header <- function() {
  paste0(
    "# Clinical Trial Response Analysis\n",
    "# Generated by dashResponse on ", Sys.Date(), "\n",
    "# This script contains reproducible code from your analysis\n\n"
  )
}

generate_libraries_code <- function(format = "rmd") {
  libraries <- c(
    "library(dplyr)",
    "library(plotly)", 
    "library(ggplot2)",
    "library(readr)",
    "library(lubridate)"
  )
  
  if (format %in% c("rmd", "qmd")) {
    paste0(
      "```{r setup, include=FALSE}\n",
      "knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)\n\n",
      "# Load required libraries\n",
      paste(libraries, collapse = "\n"),
      "\n```\n"
    )
  } else {
    paste0(
      "# Load required libraries\n",
      paste(libraries, collapse = "\n"),
      "\n"
    )
  }
}

generate_timeline_code <- function(config, static_version = FALSE, format = "rmd") {
  if (format %in% c("rmd", "qmd")) {
    chunk_start <- "```{r timeline-plot, fig.width=10, fig.height=6}\n"
    chunk_end <- "\n```\n"
  } else {
    chunk_start <- ""
    chunk_end <- ""
  }
  
  plotly_code <- paste0(
    "# Response Timeline Plot\n",
    "timeline_plot <- plot_ly(\n",
    "  data = processed_data,\n",
    "  x = ~assessment_date,\n",
    "  y = ~patient_id,\n",
    "  color = ~response,\n",
    "  type = 'scatter',\n",
    "  mode = '", if(config$connect_points) "lines+markers" else "markers", "',\n",
    "  marker = list(size = ", config$point_size * 3, ")\n",
    ") %>%\n",
    "  layout(\n",
    "    title = '", config$title, "',\n",
    "    xaxis = list(title = '", config$x_label, "', showgrid = ", tolower(config$show_grid), "),\n",
    "    yaxis = list(title = '", config$y_label, "', showgrid = ", tolower(config$show_grid), "),\n",
    "    showlegend = ", tolower(config$show_legend), ",\n",
    "    font = list(size = ", config$font_size, ")\n",
    "  )\n\n",
    "timeline_plot\n"
  )
  
  static_code <- if (static_version) {
    paste0(
      "\n# Static ggplot2 version for PDF export\n",
      "timeline_static <- ggplot(processed_data, aes(x = assessment_date, y = patient_id)) +\n",
      "  geom_point(aes(color = response), size = ", config$point_size, ") +\n",
      if(config$connect_points) "  geom_line(aes(group = patient_id, color = response)) +\n" else "",
      "  labs(\n",
      "    title = '", config$title, "',\n",
      "    x = '", config$x_label, "',\n",
      "    y = '", config$y_label, "'\n",
      "  ) +\n",
      "  theme_minimal(base_size = ", config$font_size, ") +\n",
      "  theme(legend.position = ", if(config$show_legend) "'right'" else "'none'", ")\n\n",
      "print(timeline_static)\n"
    )
  } else ""
  
  paste0(chunk_start, plotly_code, static_code, chunk_end)
}

generate_waterfall_code <- function(config, static_version = FALSE, format = "rmd") {
  if (format %in% c("rmd", "qmd")) {
    chunk_start <- "```{r waterfall-plot, fig.width=10, fig.height=6}\n"
    chunk_end <- "\n```\n"
  } else {
    chunk_start <- ""
    chunk_end <- ""
  }
  
  code <- paste0(
    "# Waterfall Plot - Best Response\n",
    "waterfall_data <- processed_data %>%\n",
    "  group_by(patient_id) %>%\n",
    "  summarise(\n",
    "    best_change = min(percent_change, na.rm = TRUE),\n",
    "    best_response = first(response[which.min(percent_change)]),\n",
    "    .groups = 'drop'\n",
    "  ) %>%\n",
    "  filter(!is.infinite(best_change))",
    if(config$sort) " %>%\n  arrange(best_change)" else "",
    "\n\n",
    "waterfall_plot <- plot_ly(\n",
    "  data = waterfall_data,\n",
    "  x = ~factor(patient_id, levels = patient_id),\n",
    "  y = ~best_change,\n",
    if(config$color_by_response) "  color = ~best_response,\n" else "",
    "  type = 'bar'\n",
    ") %>%\n",
    "  layout(\n",
    "    title = '", config$title, "',\n",
    "    xaxis = list(title = '", config$x_label, "'),\n",
    "    yaxis = list(title = '", config$y_label, "'),\n",
    "    font = list(size = ", config$font_size, ")\n",
    "  )",
    if(config$show_response_line) " %>%\n  add_hline(y = -30, line = list(color = 'green', dash = 'dash')) %>%\n  add_hline(y = 20, line = list(color = 'red', dash = 'dash'))" else "",
    "\n\nwaterfall_plot\n"
  )
  
  paste0(chunk_start, code, chunk_end)
}

generate_session_info_code <- function(format = "rmd") {
  if (format %in% c("rmd", "qmd")) {
    paste0(
      "## Session Information\n\n",
      "```{r session-info}\n",
      "sessionInfo()\n",
      "```\n"
    )
  } else {
    "# Session Information\nsessionInfo()\n"
  }
}